/* ================================================================
   ASHUTOSH KESARI PORTFOLIO — RENDER ENGINE
   ================================================================
   This file reads the CONTENT object from content.js
   and builds the entire page automatically.
   DO NOT EDIT THIS FILE — edit content.js instead.
   ================================================================ */

(function () {
  var C = CONTENT;

  /* ── HELPERS ── */
  function el(id) { return document.getElementById(id); }
  function delay(i) { return 'transition-delay:' + (0.1 + i * 0.1) + 's'; }

  /* ── PAGE META ── */
  document.title = C.name + ' — Creator | Historian | Photographer';
  el('pageDesc').setAttribute('content', C.name + ' — ' + C.tagline);

  /* ── HERO ── */
  el('heroSmall').textContent      = C.heroSmall;
  el('heroLine1').textContent      = C.heroLine1;
  el('heroLine2').textContent      = C.heroLine2;
  el('heroQuote').innerHTML        = '\u201c' + C.heroQuote + '\u201d';
  el('heroStatus').textContent     = C.heroStatus;
  el('followerCount').textContent  = C.followerCount;
  el('followerLabel').textContent  = C.followerLabel;

  /* Portrait — use data URI if embedded, else file path */
  var img = el('portraitImg');
  if (C.portrait && C.portrait !== '') {
    img.src = C.portrait;
  } else if (C.portraitBase64 && C.portraitBase64 !== '') {
    img.src = 'data:image/jpeg;base64,' + C.portraitBase64;
  } else {
    /* fallback placeholder */
    img.style.display = 'none';
    img.parentElement.style.background = 'linear-gradient(135deg, #2d1208, #5c2810)';
  }

  /* Role pills */
  var roles = C.tagline.split('•').map(function (r) { return r.trim(); }).filter(Boolean);
  el('heroRoles').innerHTML = roles.map(function (r) {
    return '<span class="role-pill">' + r + '</span>';
  }).join('');

  /* ── ABOUT ── */
  el('bioPara').innerHTML = C.bio;
  el('skillsChips').innerHTML = C.skills.map(function (s) {
    return '<span class="skill-chip">' + s + '</span>';
  }).join('');

  el('educationTimeline').innerHTML = C.education.map(function (e, i) {
    return '<div class="tl-item">' +
      '<div class="tl-dot">' + e.label + '</div>' +
      '<div class="tl-content">' +
        '<div class="tl-year">' + e.period + '</div>' +
        '<div class="tl-heading">' + e.title + '</div>' +
        '<div class="tl-sub">' + e.detail + '</div>' +
      '</div>' +
    '</div>';
  }).join('');

  /* ── PROJECTS ── */
  el('projectsGrid').innerHTML = C.projects.map(function (p, i) {
    var thumb = p.image
      ? '<img src="' + p.image + '" alt="' + p.name + '" loading="lazy" style="width:100%;height:100%;object-fit:cover">'
      : '<span style="font-size:52px;position:relative;z-index:1">' + p.emoji + '</span>';
    return '<a href="' + p.link + '" class="project-card reveal" style="' + delay(i) + '" target="_blank" rel="noopener">' +
      '<div class="project-thumb" style="background:' + p.bg + '">' + thumb +
        '<div style="position:absolute;inset:0;background:linear-gradient(to bottom,transparent 40%,rgba(0,0,0,0.5))"></div>' +
      '</div>' +
      '<div class="project-body">' +
        '<span class="project-tag">' + p.tag + '</span>' +
        '<div class="project-name">' + p.name + '</div>' +
        '<p class="project-desc">' + p.desc + '</p>' +
        '<span class="project-link">Visit Project &rarr;</span>' +
      '</div>' +
    '</a>';
  }).join('');

  /* ── PHOTOGRAPHY ── */
  el('photoGrid').innerHTML = C.photos.map(function (p, i) {
    var inner = p.image
      ? '<img src="' + p.image + '" alt="' + p.title + '" loading="lazy" ' +
        'style="width:100%;height:100%;object-fit:cover;transition:transform 0.5s cubic-bezier(.22,.68,0,1.2)">'
      : '<div class="photo-placeholder">' +
          '<span class="ph-icon">' + p.emoji + '</span>' +
          '<span class="ph-label">' + p.title + '</span>' +
        '</div>';
    return '<div class="photo-item reveal" style="' + delay(i) + ';background:' + p.bg + '">' +
      inner +
      '<div class="photo-overlay">' +
        '<div>' +
          '<div class="photo-title">' + p.title + '</div>' +
          '<div class="photo-meta">' + p.location + ' &middot; ' + p.year + '</div>' +
        '</div>' +
      '</div>' +
    '</div>';
  }).join('');

  /* Zoom on actual images inside photo-items */
  document.querySelectorAll('.photo-item img').forEach(function (img) {
    img.parentElement.addEventListener('mouseenter', function () {
      img.style.transform = 'scale(1.07)';
    });
    img.parentElement.addEventListener('mouseleave', function () {
      img.style.transform = 'scale(1)';
    });
  });

  /* ── PERSONAL FAVOURITES (grouped) ── */
  var personalContainer = el('personalGrid');
  personalContainer.innerHTML = '';

  /* Local observer for dynamically added reveal elements */
  var personalRevealObs = new IntersectionObserver(function (entries) {
    entries.forEach(function (entry) {
      if (entry.isIntersecting) {
        entry.target.classList.add('visible');
        personalRevealObs.unobserve(entry.target);
      }
    });
  }, { threshold: 0.1 });

  C.personalPics.forEach(function (group, gi) {

    /* Group heading */
    var heading = document.createElement('div');
    heading.className = 'personal-group-heading reveal';
    heading.innerHTML = '<span class="personal-group-title">' + group.title + '</span>';
    personalContainer.appendChild(heading);
    personalRevealObs.observe(heading);

    /* Grid for this group */
    var grid = document.createElement('div');
    grid.className = 'personal-grid personal-group-grid';
    personalContainer.appendChild(grid);

    group.photos.forEach(function (p, pi) {
      var inner = p.image
        ? '<img class="pi-img" src="' + p.image + '" alt="' + p.caption + '" loading="lazy" draggable="false">' +
          '<div class="img-shield"></div>'
        : '<div class="personal-placeholder">' +
            '<span class="pi-emoji">' + p.emoji + '</span>' +
          '</div>';

      var card = document.createElement('div');
      card.className = 'personal-item reveal';
      card.style.cssText = 'transition-delay:' + (0.05 * pi) + 's;background:' + p.bg;
      card.innerHTML = inner +
        '<div class="pi-overlay"></div>' +
        '<div class="pi-caption">' + p.caption + '</div>';
      grid.appendChild(card);
      personalRevealObs.observe(card);
    });

  });

  /* ── SOCIAL CARDS ── */
  el('socialGrid').innerHTML = C.socialCards.map(function (s, i) {
    return '<a href="' + s.url + '" class="social-card ' + s.type + ' reveal" style="' + delay(i) + '" target="_blank" rel="noopener">' +
      '<span class="social-icon">' + s.icon + '</span>' +
      '<div class="social-name">' + s.platform + '</div>' +
      '<div class="social-handle">' + s.handle + '</div>' +
      '<span class="social-btn">' + s.btnText + '</span>' +
    '</a>';
  }).join('');

  /* ── DESIGN GRID ── */
  el('designGrid').innerHTML = C.designs.map(function (d, i) {
    var thumb = d.image
      ? '<img src="' + d.image + '" alt="' + d.title + '" loading="lazy" ' +
        'style="width:100%;height:100%;object-fit:cover">'
      : '<div class="design-thumb">' + d.emoji + '</div>';
    return '<div class="design-card reveal" style="' + delay(i) + ';background:' + d.bg + '">' +
      thumb +
      '<div class="design-overlay">' +
        '<div class="d-title">' + d.title + '</div>' +
        (d.link !== '#' ? '<a href="' + d.link + '" target="_blank" rel="noopener" class="d-preview">&#9654; Preview</a>'
                        : '<span class="d-preview">&#9654; Preview</span>') +
      '</div>' +
    '</div>';
  }).join('');

  /* ── POETRY GRID ── */
  var moodBg = {
    rose: 'linear-gradient(160deg,#3a0d1a,#7a1a3a)',
    ink:  'linear-gradient(160deg,#0d0f2a,#1a1f4a)',
    gold: 'linear-gradient(160deg,#2a1800,#5c3a00)',
    sage: 'linear-gradient(160deg,#0a1e0e,#1a3a22)',
    dusk: 'linear-gradient(160deg,#1a0f2a,#2a1a4a)'
  };

  el('poetryGrid').innerHTML = C.poems.map(function (p, i) {
    var bg = moodBg[p.mood] || moodBg.ink;
    var inner = p.image
      ? '<img class="pc-img protected-img" src="' + p.image + '" alt="' + p.title + '" loading="lazy" draggable="false">' +
        '<div class="img-shield"></div>'
      : '<div class="poem-placeholder">' +
          '<span class="pp-emoji">' + p.emoji + '</span>' +
          '<span class="pp-title">' + p.title + '</span>' +
        '</div>';
    return '<div class="poem-card reveal" data-mood="' + p.mood + '" data-index="' + i + '"' +
      ' style="' + delay(i) + ';background:' + bg + '">' +
      inner +
      '<div class="pc-overlay"></div>' +
      '<div class="pc-info">' +
        '<span class="pc-lang">' + p.lang + '</span>' +
        '<div class="pc-title">' + p.title + '</div>' +
        '<div class="pc-year">' + p.year + '</div>' +
      '</div>' +
      '<div class="pc-expand">&#x26F6;</div>' +
    '</div>';
  }).join('');

  /* ── LIGHTBOX ── */
  var lbEl    = el('lightbox');
  var lbImg   = el('lbImg');
  var lbTitle = el('lbTitle');
  var lbMeta  = el('lbMeta');
  var lbClose = el('lbClose');
  var lbPrev  = el('lbPrev');
  var lbNext  = el('lbNext');
  var currentLbIndex = 0;
  var lbPoems = C.poems.filter(function (p) { return p.image && p.image !== ''; });

  function openLightbox(poem) {
    if (!poem.image || poem.image === '') return; // no image to show
    currentLbIndex = lbPoems.indexOf(poem);
    lbImg.src      = poem.image;
    lbTitle.textContent = poem.title;
    lbMeta.textContent  = poem.lang + ' · ' + poem.year;
    lbEl.classList.add('open');
    document.body.style.overflow = 'hidden';
  }

  function closeLightbox() {
    lbEl.classList.remove('open');
    document.body.style.overflow = '';
    lbImg.src = '';
  }

  function lbGo(dir) {
    if (lbPoems.length === 0) return;
    currentLbIndex = (currentLbIndex + dir + lbPoems.length) % lbPoems.length;
    var p = lbPoems[currentLbIndex];
    lbImg.src = p.image;
    lbTitle.textContent = p.title;
    lbMeta.textContent  = p.lang + ' · ' + p.year;
  }

  document.querySelectorAll('.poem-card').forEach(function (card) {
    card.addEventListener('click', function () {
      var idx = parseInt(card.getAttribute('data-index'));
      openLightbox(C.poems[idx]);
    });
  });

  lbClose.addEventListener('click', closeLightbox);
  lbPrev.addEventListener('click', function () { lbGo(-1); });
  lbNext.addEventListener('click', function () { lbGo(1); });

  lbEl.addEventListener('click', function (e) {
    if (e.target === lbEl) closeLightbox();
  });

  document.addEventListener('keydown', function (e) {
    if (!lbEl.classList.contains('open')) return;
    if (e.key === 'Escape')      closeLightbox();
    if (e.key === 'ArrowRight')  lbGo(1);
    if (e.key === 'ArrowLeft')   lbGo(-1);
  });

  /* ── COMMUNITIES ── */
  el('communitiesGrid').innerHTML = C.communities.map(function (c, i) {
    return '<a href="' + c.link + '" class="community-card reveal" style="' + delay(i) + '">' +
      '<div class="comm-icon">' + c.icon + '</div>' +
      '<div class="comm-name">' + c.name + '</div>' +
      '<div class="comm-sub">' + c.sub + '</div>' +
      '<p class="comm-desc">' + c.desc + '</p>' +
      '<span class="comm-link">Visit Community &rarr;</span>' +
    '</a>';
  }).join('');

  /* ── CONTACT ── */
  el('contactTagline').textContent = C.contactTagline;
  el('footerName').textContent     = C.name;

  var socialIconMap = {
    youtube:   { icon: '▶️',  title: 'YouTube'   },
    instagram: { icon: '📸', title: 'Instagram' },
    linkedin:  { icon: '💼', title: 'LinkedIn'  },
    github:    { icon: '🐙', title: 'GitHub'    }
  };
  el('contactLinks').innerHTML = Object.keys(C.social).map(function (key) {
    var s = socialIconMap[key] || { icon: '🔗', title: key };
    return '<a href="' + C.social[key] + '" class="contact-icon-link" title="' + s.title + '" target="_blank" rel="noopener">' +
      s.icon + '</a>';
  }).join('');

})();
